Update de.json
oznu/homebridge-config-ui-x pull request #845
Opened 2020-09-14 14:15 UTC by sschuste

2020-09-16 08:33 UTC, TautFlorian requested changes
There are some misspellings and my opinions about some of the changes you made. 
Would appreciate to hear your thoughts on this.

2020-09-16 08:33 UTC, TautFlorian commented on ui/src/i18n/de.json
> +    "logs.title_truncate_log_file": "Logdatei abscheiden",
There is a misspelling. Should be `Logdatei abschneiden`

2020-09-16 08:33 UTC, TautFlorian commented on ui/src/i18n/de.json
> +    "logs.message_download_warning": "ACHTUNG: Homebridge-Logdateien können persönliche Informationen, Passwörter or Zugrifftokens beinhalten. Bitte sieh dir die Logdatei an und entferne alle sensiti
`or` should be translated as well to `oder` maybe `und/oder` would fit even better.

2020-09-16 08:33 UTC, TautFlorian commented on ui/src/i18n/de.json
> +    "backup.message_restore_warning": "Durch das Wiederherstellen von einem Backup wird die aktuelle Homebridge-Konfiguration unwiderruflich überschreiben.",
`überschreiben` should be `überschrieben`

2020-09-16 08:33 UTC, TautFlorian commented on ui/src/i18n/de.json
> +    "reset.message_remove_cached_accessories_single_warning": "Mit Vorsicht verwenden. Das Entfernen bestimmter Geräte vom Cache kann unbeabsichtigte Folgen haben.",
Should be `aus dem Cache`

2020-09-16 08:33 UTC, TautFlorian commented on ui/src/i18n/de.json
> +    "reset.title_unpair_bridges_cameras_tv_external_accessories": "Entkoppele Bridges / Kameras / Fernseher / externes Zubehör",
Should be `Entkopple`

2020-09-16 08:33 UTC, TautFlorian commented on ui/src/i18n/de.json
> +    "settings.title_manage_cached_accessories": "Verwalten von Geräten im Cache",
In my opinion this translation isn't better than the one before.
I would not translate it this way.

2020-09-16 08:36 UTC, TautFlorian requested changes

2020-09-16 08:36 UTC, TautFlorian commented on ui/src/i18n/de.json
> +    "logs.message_log_file_truncated": "Logdatei abgeschnitten.",
Maybe we should talk generally about dots. In this case there is a dot added to the line but in most cases there is none.
We should decide for one option, in my eyes we shouldn't add a line ending point.

2020-09-17 09:36 UTC, oznu commented
@sschuste - I'll wait for your comment on the above before merging 😄 

Thanks everyone for contributing!

2020-09-22 12:25 UTC, TautFlorian commented
@oznu  I'm going to create a pull request by my own fixing `de.json` this evening because @sschuste seems not to be very active.

2020-10-03 09:20 UTC, oznu commented
I'll merge this. @TautFlorian - feel free to do another PR with any changes you think improve the translation further 😄 

Thanks @sschuste

2020-10-03 09:21 UTC, merged